export type BookingInitRequestDto = {
    stationId: string;
    size: "S" | "M" | "L";
    expectedEndTime: string;
};

export type BookingRecordDto = {
    bookingId: string;
    operationId?: string;
    userId: string;
    stationId: string;
    lockerBoxId: string;
    size: "S" | "M" | "L";
    status: string;
    lockerStatus?: string;
    paymentStatus?: string;
    expectedEndTime: string;
    expiresAt?: string;
    ttl?: number;
    price: number;
    currency: string;
    paymentProvider?: string;
    paymentSessionId?: string;
    paymentIntentId?: string;
    providerPaymentId?: string;
    paymentUrl?: string;
    amount?: number;
    paymentConfirmedAt?: string;
    extendOperationId?: string;
    pendingExtendExpectedEndTime?: string;
    extendPaymentStatus?: string;
    extendPaymentSessionId?: string;
    extendPaymentIntentId?: string;
    extendProviderPaymentId?: string;
    extendPaymentUrl?: string;
    extendAmount?: number;
    extendCurrency?: string;
    extendPaymentConfirmedAt?: string;
    startTime?: string;
    createdAt: string;
    updatedAt: string;
};
